# Generated by Django 2.2.2 on 2020-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_nom', models.CharField(max_length=100)),
                ('restaurant_telefon', models.CharField(max_length=50)),
                ('restaurant_descripcio', models.TextField()),
                ('restaurant_email', models.CharField(max_length=100)),
                ('restaurant_web', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('usuari_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuari_nom', models.CharField(max_length=100)),
                ('usuari_email', models.CharField(max_length=100)),
            ],
        ),
    ]
