# Generated by Django 2.2.2 on 2020-03-22 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_direccio',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
