# Generated by Django 3.0.4 on 2020-03-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant_restaurant_direccio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaRestaurant',
            fields=[
                ('multimedia_id', models.AutoField(primary_key=True, serialize=False)),
                ('multimedia_imatge', models.ImageField(default='pic_folder/none/no-img.jpg', upload_to='pic_folder/')),
                ('fk_restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
            ],
        ),
    ]
