# Generated by Django 3.0.4 on 2020-06-02 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fotonoticia_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
