# Generated by Django 3.0.4 on 2020-06-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200603_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esdeveniment',
            name='latitud',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='esdeveniment',
            name='longitud',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
