# Generated by Django 3.0.4 on 2020-05-29 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foto',
            new_name='fotoperfil',
        ),
        migrations.AddField(
            model_name='profile',
            name='direccio',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nomillinatges',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
