# Generated by Django 3.0.4 on 2020-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200603_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esdeveniment',
            name='latitud',
            field=models.DecimalField(decimal_places=5, max_digits=30),
        ),
        migrations.AlterField(
            model_name='esdeveniment',
            name='longitud',
            field=models.DecimalField(decimal_places=5, max_digits=30),
        ),
        migrations.AlterField(
            model_name='esdeveniment',
            name='titol',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titol',
            field=models.CharField(max_length=400),
        ),
    ]
