# Generated by Django 3.0.4 on 2020-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200603_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='esdeveniment',
            name='descripcio',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
