# Generated by Django 3.0.4 on 2020-06-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200604_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonoticia',
            name='imatge',
            field=models.ImageField(default='../../../static/images/pic_noticia/none/no-img.jpg', upload_to='../../../static/images/pic_noticia/'),
        ),
        migrations.AlterField(
            model_name='fotorestaurant',
            name='imatge',
            field=models.ImageField(default='static/images/pic_restaurant/none/no-img.jpg', upload_to='static/images/pic_restaurant/'),
        ),
        migrations.AlterField(
            model_name='fotorestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_restaurant', to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fotoperfil',
            field=models.ImageField(default='static/images/pic_perfil/none/no-img.jpg', upload_to='static/images/pic_perfil/'),
        ),
        migrations.AlterField(
            model_name='suggeriment',
            name='imatge_restaurant',
            field=models.ImageField(blank=True, default='../../../static/images/pic_restaurant/none/no-img.jpg', null=True, upload_to='../../../static/images/pic_restaurant/'),
        ),
    ]
