# Generated by Django 3.0.4 on 2020-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200604_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonoticia',
            name='imatge',
            field=models.ImageField(default='pic_noticia/none/no-img.jpg', upload_to='pic_noticia/'),
        ),
        migrations.AlterField(
            model_name='fotorestaurant',
            name='imatge',
            field=models.ImageField(default='pic_restaurant/none/no-img.jpg', upload_to='pic_restaurant/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fotoperfil',
            field=models.ImageField(default='pic_perfil/none/no-img.jpg', upload_to='pic_perfil/'),
        ),
        migrations.AlterField(
            model_name='suggeriment',
            name='imatge_restaurant',
            field=models.ImageField(blank=True, default='pic_restaurant/none/no-img.jpg', null=True, upload_to='pic_restaurant/'),
        ),
    ]
