# Generated by Django 3.0.4 on 2020-06-06 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200604_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='valoracio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='suggeriment',
            name='telefon',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.CreateModel(
            name='ComentarisRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missatge', models.CharField(max_length=500)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris_restaurant', to='api.Restaurant')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentaris_restaurant_usuari', to='api.Profile')),
            ],
        ),
    ]
