# Generated by Django 3.0.4 on 2020-06-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200606_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarirestaurant',
            old_name='usuari',
            new_name='profile',
        ),
    ]
