# Generated by Django 3.0.4 on 2020-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200606_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarirestaurant',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comentarirestaurant',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
