# Generated by Django 3.0.4 on 2020-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200606_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='horari',
            field=models.CharField(default="L'horari no està disponible", max_length=500),
            preserve_default=False,
        ),
    ]
