# Generated by Django 3.0.4 on 2020-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_restaurant_horari'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotorestaurant',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='valoraciorestaurant',
            unique_together={('profile', 'valoracio')},
        ),
        migrations.DeleteModel(
            name='Suggeriment',
        ),
        migrations.DeleteModel(
            name='TipusSuggeriment',
        ),
    ]
