# Generated by Django 3.0.4 on 2020-06-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200608_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotorestaurant',
            name='visible',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
    ]
