# Generated by Django 3.0.4 on 2020-06-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200608_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_usuari', to='api.Profile'),
            preserve_default=False,
        ),
    ]
