# Generated by Django 3.0.4 on 2020-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_restaurant_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='responsable',
            field=models.BooleanField(default=False),
        ),
    ]
