# Generated by Django 3.0.4 on 2020-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_restaurant_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30),
        ),
    ]
