# Generated by Django 3.0.7 on 2020-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200611_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='horari',
            field=models.CharField(blank=True, default="L'horari no està disponible", max_length=500),
        ),
    ]
