# Generated by Django 3.0.7 on 2020-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200613_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imatge',
            field=models.ImageField(default='pic_restaurant/none/no-img.jpg', upload_to='pic_restaurant/'),
        ),
    ]
