# Generated by Django 3.0.7 on 2020-06-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200614_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='web',
            field=models.CharField(blank=True, default='-', max_length=1000),
        ),
        migrations.CreateModel(
            name='SuggerimentRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missatge', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggeriment_restaurant_usuari', to='api.Profile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggeriment_restaurant', to='api.Restaurant')),
            ],
        ),
    ]
